### ISSUE TITLE
resizeEvents test case seems to require sizing the tested window below a certain width

### ISSUE THREAD

**Issue by johnjbarton** [google/qpp#47]
I recall this limitation was chosen as a compromise to move forward, but I think we should test the window width and throw an error if it is too large so we don't run the test then puzzle over why its not working.

**Comment by curcio** [comment]
Actually, it's supposed to work. The problem I have is that it gets TIMEOUT if the window width is too big. I think I know of an alternative way that might work better.

The problem I had with this test case is that I need to wait for a turn number that isn't known until I get the window width. So I'm checking the width after many clicks without waiting for a certain the turn. As a result, I sometimes receive FAIL because I haven't reached the last turn yet, but if I check manually with the inspector once the test runs, the size is 9px as it should be.

**Comment by johnjbarton** [comment]
What happens if you check the window width in an eval in panel then throw in the test case if the value is too large?
