### ISSUE TITLE
Console area grows in size 

### ISSUE THREAD

**Issue by johnjbarton** [google/qpp#7]
Once the number of messages exceeds the size of the console area, it begins to grow. Instead it should scroll such that the latest message is at the bottom of the console area,

**Comment by curcio** [comment]
I was trying a CSS solution for this but it seems that the CSS property resize is not that well supported, for example, if you actually try resizing a little the window before doing anything then the console area doesn't grow when messages start appearing. 

Related to this issue is that if you have a long message list, if you close the debugger window, and open it up again, the console size is at maximum size and is not resizable. 

An alternative solution I was thinking would be having a separator div that can be dragged vertically to adjust the console size. Another option would be to rely on a library

**Comment by johnjbarton** [comment]
Test case passes now, height is fixed.
